name = "mygamelist"
main = "src/index.js"
compatibility_date = "2024-01-01"

pages_build_configuration = {}

[build]
command = "npm run build"
cwd = "./"

[env.production]
routes = [
  { pattern = "mygamelist.pages.dev/*", zone_name = "" }
]
vars = { ENVIRONMENT = "production" }
