import type { IconName } from './icons';
import { TAB_IDS, type TabId } from '../../model/types/game';

export interface TabAction {
  target: TabId;
  label: string;
  btnCls: string;
  icon: IconName;
}

export const TAB_ORDER: TabId[] = [...TAB_IDS];

export const TAB_TITLES: Record<TabId, string> = {
  c: 'Lista del completista',
  v: 'Lista de la vergüenza',
  e: 'En curso',
  p: 'Lista de próximos',
};

export const TAB_TOOLTIPS: Record<TabId, string> = {
  c: 'Completados',
  v: 'Abandonados',
  e: 'En curso',
  p: 'Próximos',
};

export const TAB_ROUTE: Record<TabId, string> = {
  c: '/completados',
  v: '/visitados',
  e: '/en-curso',
  p: '/proximos',
};

export const ROUTE_TAB: Record<string, TabId> = {
  '/completados': 'c',
  '/visitados': 'v',
  '/en-curso': 'e',
  '/proximos': 'p',
};

export const TAB_ACTIONS: Record<TabId, TabAction[]> = {
  c: [{ target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' }],
  v: [
    { target: 'c', label: 'Pasar a completados', btnCls: 'btn-complete', icon: 'trophy' },
    { target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' },
  ],
  e: [
    { target: 'c', label: 'Pasar a completados', btnCls: 'btn-complete', icon: 'trophy' },
    { target: 'v', label: 'Pasar a abandonados', btnCls: 'btn-abandoned', icon: 'abandoned' },
  ],
  p: [{ target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' }],
};

export const FILTER_BOOL: Record<TabId, { field: 'replayable' | 'retry'; label: string } | null> = {
  c: { field: 'replayable', label: 'Rejugar' },
  v: { field: 'retry', label: '¿Dar otra oportunidad?' },
  e: null,
  p: null,
};

export const SYNC_BADGE_TEXT = {
  idle: 'No sincronizado',
  ok: 'Sincronizado',
  syncing: 'Sincronizando…',
  error: 'Error de sincronización',
} as const;

export const DIALOG_MESSAGES = {
  deleteTagTitle: (tag: string) => `¿Eliminar etiqueta "${tag}"?`,
  cancel: 'Cancelar',
  confirmDelete: 'Eliminar',
} as const;

export const VALIDATION_MESSAGES = {
  yearInvalid: 'El año debe tener exactamente 4 dígitos. Pulsa Guardar de nuevo para ignorarlo.',
  fieldsInvalid: 'Revisa los campos marcados antes de guardar.',
  tagExists: 'Ya existe. Pulsa Guardar otra vez para fusionar.',
  tagMerged: 'Fusionado correctamente',
  tagUpdated: 'Actualizado correctamente',
  scoreRequired: 'Selecciona una puntuación',
} as const;

export const SYNC_MESSAGES = {
  needsConfiguration: 'Primero configura la sincronización.',
  connectSuccess: 'Sincronización configurada',
  connectError: 'Error al conectar sincronización',
  syncSuccess: 'Datos sincronizados',
  syncError: 'Error al sincronizar',
  initError: 'Error de sincronización',
  offline: 'Sin conexión: se reintentará al recuperar la red',
  syncInProgress: 'Sincronización ya en curso',
  disconnectSuccess: 'Sincronización desconectada',
  copySuccess: 'Gist ID copiado al portapapeles',
  copyError: 'No se pudo copiar el Gist ID',
  copyMissing: 'No hay Gist ID disponible para copiar',
  recoverSuccess: 'Gist ID recuperado desde Google',
  recoverMissingInProfile: 'No se encontró gamesGistId en tu perfil de Google/Firestore',
  recoverMissingTokenInProfile: 'No se encontró el token en tu perfil de Google/Firestore',
  recoverError: 'No se pudo recuperar el Gist ID desde Google',
} as const;

export const UI_MESSAGES = {
  admin: {
    noTags: 'No hay etiquetas',
    editPlaceholder: 'Escribe el nuevo valor',
    editBtn: 'Editar',
    deleteBtn: 'Eliminar',
    editCancelBtn: 'Cancelar',
    editSaveBtn: 'Guardar',
    closeAria: 'Cerrar modal',
  },
  form: {
    enterToAddHint: 'Pulsa Enter para añadir',
    newTitle: 'Nuevo juego',
    editTitle: 'Editar juego',
    nameLabel: 'Nombre *',
    namePlaceholder: 'Ej: The Witcher 3',
    genresLabel: 'Géneros',
    genresPlaceholder: 'Ej: Acción',
    platformsLabel: 'Plataformas',
    platformsPlaceholder: 'Ej: PC',
    scoreLabel: 'Puntuación',
    interestLabel: 'Interés',
    yearsLabel: 'Años completado',
    yearsPlaceholder: (year: number) => `Ej: ${year}`,
    hoursLabel: 'Horas jugadas',
    hoursPlaceholder: 'Ej: 120',
    strengthsLabel: 'Puntos fuertes',
    strengthsPlaceholder: 'Ej: Combate',
    weaknessesLabel: 'Puntos débiles',
    weaknessesPlaceholder: 'Ej: Repetitivo',
    reasonsLabel: 'Razones',
    reasonsPlaceholder: 'Ej: Falta de tiempo',
    steamDeck: 'Steam Deck',
    reviewLabel: 'Análisis',
    reviewPlaceholder: 'Ej: Historia sólida, combate excelente y gran ambientación.',
    charCount: (count: number, max: number) => `${count.toLocaleString()} / ${max.toLocaleString()} caracteres`,
    // A11y-3: mensajes de umbral para lectores de pantalla (texto constante por banda → se anuncian una vez al
    // cruzar el umbral, no en cada pulsación). El conteo numérico se deja como texto visible SIN aria-live.
    charNearLimit: 'Te acercas al límite de caracteres del análisis.',
    charLimitReached: 'Has alcanzado el límite de caracteres del análisis.',
    cancel: 'Cancelar',
    save: 'Guardar',
  },
  appTitle: 'Mis Listas',
  nav: {
    ariaLabel: 'Navegación principal',
    lists: 'Listados',
    social: 'Social',
    settings: 'Ajustes',
  },
  toolbar: {
    searchPlaceholder: 'Buscar',
    steamDeck: 'Steam Deck',
    removeFilter: (label: string) => `Quitar filtro ${label}`,
    genre: 'Género',
    allGenres: 'Todos los géneros',
    platform: 'Plataforma',
    allPlatforms: 'Todas las plataformas',
    score: 'Puntuación',
    anyScore: 'Cualquier puntuación',
    scoreOrMore: (value: number) => `${value} o más`,
    hours: 'Horas',
    anyDuration: 'Cualquier duración',
  },
  starPicker: {
    groupAria: 'Seleccionar puntuación',
    starAria: (star: number) => `${star} estrella${star > 1 ? 's' : ''}`,
  },
  table: {
    edit: 'Editar',
    delete: 'Eliminar',
    rowDetailsAria: (expanded: boolean, name: string) => `${expanded ? 'Contraer' : 'Expandir'} detalles de ${name}`,
    actionAria: (label: string, name: string) => `${label} - ${name}`,
    editAria: (name: string) => `Editar - ${name}`,
    deleteAria: (name: string) => `Eliminar - ${name}`,
    removeTag: (value: string) => `Eliminar ${value}`,
    emptyTitle: 'No hay juegos aquí todavía',
    emptyCta: 'Añadir juego',
    moreCount: (count: number) => `+${count}`,
    replayHeaderTip: 'Indica si el juego es rejugable',
    retryHeaderTip: 'Indica si merece otra oportunidad',
    sortHeaderTip: (column: string) => `Ordenar por ${column.toLowerCase()}`,
  },
  detail: {
    platforms: 'Plataformas',
    steamDeck: 'Steam Deck',
    genres: 'Géneros',
    yearsCompleted: 'Años en los que se completó',
    playtime: 'Tiempo jugado',
    hoursSuffix: (hours: string) => `${hours} horas`,
    strengths: 'Puntos fuertes',
    weaknesses: 'Puntos débiles',
    score: 'Puntuación',
    interest: 'Interés',
    replayability: 'Rejugabilidad',
    retry: 'Dar otra oportunidad',
    review: 'Análisis',
  },
  settings: {
    title: 'Ajustes',
    account: {
      title: 'Ajustes de cuenta',
    },
    appearance: {
      groupAria: 'Tema de la aplicación',
      light: 'Claro',
      dark: 'Oscuro',
      cycleHint: 'Pulsa para cambiar a',
      paletteAria: 'Paleta de color',
      paletteLabel: 'Tema',
      modeLabel: 'Modo',
    },
    scoreScale: {
      title: 'Puntuación',
      subtitle: 'Cómo se muestran las notas de tus juegos.',
      groupAria: 'Escala de puntuación',
      starsLabel: 'Estrellas',
      starsHint: 'Escala clásica de 0 a 5',
      gradeLabel: 'Nota 0–100',
      gradeHint: 'Aro numérico, de rojo a verde',
      lockedHint: 'Asocia tu cuenta de Google para elegir la escala (se guarda y sincroniza entre dispositivos).',
    },
    sync: {
      title: 'Sincronización',
      status: 'Estado actual',
      gistConnectedPrefix: 'Gist conectado',
      helpGithubTitle: '¿Qué es GitHub Gist?',
      helpGithubBody: 'GitHub Gist permite guardar tus listas en la nube privada para sincronizarlas entre dispositivos.',
      helpConfigTitle: 'Cómo configurar',
      helpConfigBody: 'Necesitas una cuenta de GitHub y un token personal con permiso gist para conectar tu respaldo en la nube.',
      helpConfigLinkLabel: 'Abrir configuración de tokens en GitHub',
      helpConfigLinkUrl: 'https://github.com/settings/tokens',
      helpConfigExpand: 'Ver pasos detallados',
      helpConfigCollapse: 'Ocultar pasos detallados',
      helpConfigStep1: 'Inicia sesión en GitHub o crea una cuenta si aún no la tienes.',
      helpConfigStep2: 'Abre la página de tokens y crea un token nuevo.',
      helpConfigStep3: 'Asigna un nombre descriptivo para identificarlo fácilmente.',
      helpConfigStep4: 'En fecha de caducidad selecciona Sin caducidad (o el periodo que prefieras).',
      helpConfigStep5: 'En permisos marca gist y guarda el token.',
      helpConfigStep6: 'Copia el token y pégalo en el campo Token de esta pantalla. Mantén este valor en privado.',
      helpConfigStep7: 'Si es tu primera conexión, deja el Gist ID vacío. Si ya tenías uno, pégalo para reutilizarlo.',
      tokenLabel: 'Token *',
      tokenPlaceholder: 'ghp_xxxxxxxxxxxxxxxxxxxxxxx',
      gistLabel: 'Gist ID (vacío la primera vez)',
      gistPlaceholder: 'Ej: a1b2c3d4e5f6...',
      oauthConnectBtn: 'Conectar con GitHub',
      oauthConnectingBtn: 'Conectando con GitHub...',
      oauthHelpBody: 'La forma más sencilla: te lleva a GitHub, autorizas el acceso a tus gists y volvemos conectados. Sin crear ni pegar tokens.',
      manualToggleShow: 'Prefiero introducir un token manualmente',
      manualToggleHide: 'Ocultar el modo manual',
      connectBtn: 'Conectar',
      syncBtn: 'Sincronizar',
      disconnectBtn: 'Desconectar',
      copyBtn: 'Copiar Gist ID',
      recoverBtn: 'Recuperar de Google',
      recoveringBtn: 'Recuperando...',
      copyAriaLabel: 'Copiar Gist ID',
      recoverAriaLabel: 'Recuperar Gist ID desde Google',
    },
    backup: {
      title: 'Respaldo de datos',
      note: 'Control total sobre tus listas, tanto local como en la nube.',
      description: 'Exporta o importa tus listados en formato JSON.',
      overwriteLabel: 'Sobreescribir datos existentes (local y Gist)',
      overwriteHint: 'Marcar esta opción reemplaza por completo los datos almacenados y también actualizará tu Gist cuando haya sincronización activa.',
      exportBtn: 'Exportar',
      importBtn: 'Importar',
      importAriaLabel: 'Seleccionar archivo para importar',
    },
    admin: {
      title: 'Administración de filtros',
      description: 'Gestiona géneros, plataformas y etiquetas comunes por categoría.',
      genres: 'Géneros',
      platforms: 'Plataformas',
      strengths: 'Puntos fuertes',
      weaknesses: 'Puntos débiles / razón',
      collapseAria: 'Ocultar categoría',
      expandAria: 'Mostrar categoría',
    },
  },
} as const;

// Pantalla de reemplazo del error boundary RAÍZ (fallo de render que tumbaría toda la app).
export const APP_ERROR_UI = {
  sectionAria: 'Error de la aplicación',
  title: 'Algo ha ido mal',
  body: 'La aplicación ha encontrado un error inesperado. Vuelve a cargar la página para continuar; tus datos están a salvo.',
  reload: 'Recargar',
} as const;

export const SOCIAL_UI = {
  hubTitle: 'Espacio social',
  loading: 'Cargando espacio social...',
  screenAria: 'Social',
  errorBoundary: {
    sectionAria: 'Error del espacio social',
    title: 'No se pudo mostrar el espacio social',
    body: 'Ha ocurrido un problema al cargar esta sección. El resto de la aplicación sigue disponible.',
    retry: 'Reintentar',
    // El reintento está limitado (1 cada 15 min) para no reintentar de forma indiscriminada ante un fallo persistente.
    retryIn: (minutes: number) => `Podrás reintentar en ${minutes} min`,
  },
  cardSelector: {
    searchLabel: 'Buscar',
    searchAria: (title: string) => `${title} buscador`,
    cardsAria: (title: string) => `${title} cards`,
  },
  gateway: {
    actionsAria: 'Acciones principales social',
    progressAria: 'Progreso de configuración social',
    stepsAria: 'Pasos de configuración social',
    stateAria: 'Estado de configuración social',
    flowAria: 'Flujo social',
    lead: 'Configura tu espacio social en tres pasos: conecta GitHub, valida con Google y crea tu espacio social.',
    stepCaption: (current: number, total: number) => `Paso actual: ${current} de ${total}`,
    progress: (value: number) => `${value}% completado`,
    connectSync: 'Ir a Sincronización',
    signIn: 'Continuar con Google',
    signingIn: 'Validando identidad...',
    resolveProfile: 'Comprobando perfil social...',
    createGist: 'Crear espacio social',
    creatingGist: 'Creando espacio social...',
    enterSocial: 'Entrar a la actividad',
    signOut: 'Cerrar sesión',
    syncRequired: 'Activa primero la sincronización principal con GitHub para habilitar el espacio social.',
    signInRequired: 'Tu sincronización principal está activa. Continúa con Google para validar tu perfil social.',
    gistRequired: 'Se ha verificado Firestore. Si no existe gist social asociado, crea un espacio social nuevo.',
    gistReadySignIn: 'Ya tienes gist social enlazado. Inicia sesión con Google para acceder a la actividad.',
    gistMissing: 'Aún no hay gist social enlazado.',
    detailsSummary: 'Ver estado técnico',
    stateSync: 'Sincronización',
    stateGist: 'Espacio social',
    stateSession: 'Sesión Google',
    stateConnected: 'Conectada a GitHub',
    stateNotConnected: 'No conectada',
    stateLinked: 'Enlazado',
    stateNotLinked: 'No enlazado',
    stateActive: 'Activa',
    stateNotStarted: 'No iniciada',
    flow: ['1. GitHub', '2. Google', '3. Espacio social', '4. Actividad'],
  },
  feed: {
    sectionAria: 'Social',
    title: 'Actividad social',
    subtitle: 'Descubre perfiles públicos, análisis y recomendaciones destacadas de otros jugadores.',
    actionsAria: 'Acciones de la actividad',
    activityListAria: 'Actividad social',
    toolbarAria: 'Búsqueda y filtros de la actividad',
    feedRowAria: 'Actividad social',
    profile: 'Editar mi perfil',
    openProfiles: 'Ver perfiles',
    openOwnProfile: 'Ver mi perfil',
    openRequests: 'Solicitudes',
    openRequestsAria: (count: number) =>
      count > 0 ? `Solicitudes de amistad, ${count} pendiente${count === 1 ? '' : 's'}` : 'Solicitudes de amistad',
    refresh: 'Actualizar',
    refreshing: 'Actualizando...',
    signOut: 'Cerrar sesión',
    statsProfiles: 'Perfiles visibles',
    statsFavorites: 'Favoritos publicados',
    statsActivities: 'Eventos de actividad',
    sectionTitle: 'Actividad de perfiles',
    activityTitle: 'Actividad',
    postsTitle: 'Publicaciones',
    postComposerLabel: 'Comparte una noticia o un enlace',
    postPlaceholder: 'Comparte una noticia o un enlace…',
    postPublish: 'Publicar',
    postPublishing: 'Publicando...',
    postSharedFileHint: 'Pega la URL directa de la imagen (clic derecho → «Copiar la URL de la imagen») para verla incrustada.',
    postedAt: (date: Date) =>
      `Publicado el ${date.toLocaleDateString('es-ES', { day: '2-digit' })} de ${date.toLocaleDateString('es-ES', { month: 'long' })} a las ${date.toLocaleTimeString('es-ES', { hour: 'numeric', minute: '2-digit' })}`,
    loading: 'Cargando actividad...',
    empty: 'No hay perfiles visibles todavía o faltan permisos de lectura en Firestore.',
    activityEmpty: 'Aún no hay actividad de análisis para mostrar.',
    activityEmptyNoFriends: 'Tu feed muestra la actividad de tus amigos. Descubre perfiles y añade amigos para empezar a ver sus análisis y publicaciones.',
    discoverFriends: 'Descubre y añade amigos',
    openActivityAria: (name: string, gameName: string) => `Abrir detalle de actividad de ${name} sobre ${gameName}`,
    openProfileAria: (name: string) => `Abrir perfil social de ${name}`,
    analyzedRecently: 'Analizado recientemente',
    feedLoadMore: 'Mostrar más',
    analyzedAt: (date: Date) =>
      `Analizado el ${date.toLocaleDateString('es-ES', { day: '2-digit' })} de ${date.toLocaleDateString('es-ES', { month: 'long' })} a las ${date.toLocaleTimeString('es-ES', { hour: 'numeric', minute: '2-digit' })}`,
    noFavorites: 'Sin favoritos publicados',
    favoritesPrefix: 'Favoritos: ',
    reviewHeadline: (gameName: string) => `Analizó ${gameName}`,
    reviewEmpty: 'Sin comentario adicional en el análisis.',
    showMore: 'Más',
    viewDetail: 'Ver detalle',
    detailTitle: 'Detalle de actividad social',
    detailSubtitle: 'Contenido completo del análisis seleccionado.',
    detailActionsAria: 'Acciones del detalle social',
    detailMissing: 'No se encontró la actividad solicitada o ya no está disponible.',
    metadataPlatforms: 'Plataformas:',
    metadataGenres: 'Géneros:',
    metadataStrengths: 'Puntos fuertes:',
    metadataWeaknesses: 'Puntos débiles:',
    profileDetailTitle: 'Detalle de perfil social',
    profileDetailSubtitle: 'Vista pública del perfil seleccionado con sus favoritos.',
    profileDetailActionsAria: 'Acciones del detalle de perfil social',
    profileDetailMissing: 'No se encontró el perfil solicitado o ya no está disponible.',
    profileFavoritesCount: (count: number) => `${count} ${count === 1 ? 'favorito' : 'favoritos'}`,
    profileFavoritesTitle: 'Favoritos publicados',
    profileListsTitle: 'Juegos',
    roulettePick: 'Elige tu próximo juego',
    profileListsEmpty: 'Este perfil no ha publicado listados todavía.',
    profileFriendsOnly: 'Hazte amigo de este jugador para ver sus reseñas, listados y recomendaciones.',
    profileFriendsOnlyTitle: 'Perfil de amigos',
    gameFilterPlaceholder: 'Filtrar por título…',
    gameFilterEmpty: 'Ningún juego coincide con la búsqueda.',
    profileDetailRefresh: 'Actualizar listados',
    profileDetailRefreshing: 'Actualizando…',
    reviewsButton: 'Reseñas',
    reviewsBack: 'Ver perfil',
    reviewsTitle: 'Reseñas',
    reviewsEmptyProfile: 'Este perfil no ha publicado reseñas todavía.',
    reviewExpand: 'Ver más',
    reviewCollapse: 'Ver menos',
    profileListTabCompleted: 'Completados',
    profileListTabVisited: 'Abandonados',
    profileListTabPlaying: 'En curso',
    profileListTabPlanned: 'Próximos',
    backToFeed: 'Volver a la actividad',
    searchLabel: 'Buscar perfiles',
    searchPlaceholder: 'Buscar por nombre, email o juego',
    filterAll: 'Todos',
    filterFavorites: 'Con favoritos',
    resultCount: (count: number) => `${count} perfiles visibles`,
  },
  profiles: {
    sectionAria: 'Perfiles sociales',
    title: 'Perfiles',
    subtitle: 'Descubre perfiles públicos de otros jugadores y sus juegos favoritos.',
    actionsAria: 'Acciones de la pantalla de perfiles',
    toolbarAria: 'Filtro de perfiles por nombre',
    rowAria: 'Perfiles públicos',
    back: 'Volver a la actividad',
    refresh: 'Actualizar',
    refreshing: 'Actualizando...',
    searchLabel: 'Buscar por nombre',
    searchPlaceholder: 'Filtrar perfiles por nombre',
    resultCount: (count: number) => `${count} perfiles visibles`,
    loading: 'Cargando perfiles...',
    empty: 'No hay perfiles visibles todavía o faltan permisos de lectura en Firestore.',
    noFavorites: 'Sin favoritos publicados',
    openProfileAria: (name: string) => `Abrir perfil social de ${name}`,
    friendsTitle: 'Amigos',
    othersTitle: 'Descubrir',
    friendsEmpty: 'Aún no tienes amigos. Envía una petición desde la lista de abajo.',
    othersEmpty: 'No hay más perfiles que mostrar.',
  },
  requests: {
    sectionAria: 'Solicitudes de amistad',
    title: 'Solicitudes de amistad',
    subtitle: 'Gestiona las peticiones que recibes y las que has enviado.',
    actionsAria: 'Acciones de solicitudes de amistad',
    back: 'Volver a la actividad',
    incomingTitle: 'Recibidas',
    outgoingTitle: 'Enviadas',
    friendsTitle: 'Amigos',
    incomingEmpty: 'No tienes peticiones de amistad pendientes.',
    outgoingEmpty: 'No has enviado peticiones pendientes.',
    friendsEmpty: 'Aún no tienes amigos. Envía peticiones desde Perfiles.',
    loading: 'Cargando solicitudes...',
    accept: 'Aceptar',
    reject: 'Rechazar',
    cancel: 'Cancelar',
    remove: 'Dejar de ser amigos',
    acceptAria: (name: string) => `Aceptar la petición de ${name}`,
    rejectAria: (name: string) => `Rechazar la petición de ${name}`,
    cancelAria: (name: string) => `Cancelar la petición enviada a ${name}`,
    removeAria: (name: string) => `Dejar de ser amigo de ${name}`,
    unknownUser: 'Usuario',
  },
  friendship: {
    add: 'Añadir amigo',
    accept: 'Aceptar',
    pending: 'Pendiente',
    friends: 'Amigos',
    remove: 'Dejar de ser amigos',
    addAria: (name: string) => `Enviar petición de amistad a ${name}`,
    acceptAria: (name: string) => `Aceptar la petición de ${name}`,
    cancelAria: (name: string) => `Cancelar la petición enviada a ${name}`,
    removeAria: (name: string) => `Dejar de ser amigo de ${name}`,
    removeConfirmTitle: (name: string) => `¿Dejar de ser amigo de ${name}?`,
    removeConfirmAction: 'Dejar de ser amigos',
  },
  profile: {
    sectionAria: 'Social',
    actionsAria: 'Acciones del perfil social',
    title: 'Mi perfil social',
    subtitle: 'Define tu identidad pública, selecciona tus juegos clave y mantén tu perfil sincronizado.',
    toFeed: 'Ir a la actividad',
    save: 'Guardar perfil',
    saving: 'Guardando perfil...',
    signOut: 'Cerrar sesión',
    statusSynced: 'Sincronizado',
    statusUnpublished: 'Sin publicar',
    identityTitle: 'Identidad visible',
    identityDescription: 'Este nombre se mostrará en la actividad social y en análisis compartidos.',
    nameLabel: 'Nombre social',
    namePlaceholder: 'Escribe tu nombre visible',
    privacyTitle: 'Privacidad',
    privacyLabel: 'Perfil privado',
    privacyPrivate: 'Tu perfil es privado. Solo usuarios autorizados podrán verlo.',
    privacyPublic: 'Tu perfil es público. Otros usuarios podrán encontrarte por email.',
    favoritesTitle: 'Juegos favoritos',
    favoritesDescription: 'Selecciona tus juegos más representativos desde tus listas locales.',
    favoritesSearchPlaceholder: 'Buscar favorito por nombre',
    searchEmpty: 'No hay juegos que coincidan con la búsqueda.',
    hydrating: 'Cargando datos de perfil desde gist social...',
    visibilityTitle: 'Visibilidad del perfil',
    visibilityDescription: 'Configura qué partes de tus listados se comparten públicamente en el detalle social.',
    hideListSectionTitle: 'Ocultar listados',
    hideVisitedList: 'Ocultar lista de abandonados',
    hidePlayingList: 'Ocultar lista de en curso',
    hidePlannedList: 'Ocultar lista de próximos',
    hideFieldSectionTitle: 'Ocultar campos',
    hideReplayableField: 'Rejugar',
    hideRetryField: 'Dar otra oportunidad',
    hideGameTimeField: 'Tiempo jugado',
    photoSectionTitle: 'Foto de perfil',
    showPhotoField: 'Mostrar mi foto de perfil',
  },
  status: {
    needMainSync: 'Activa la sincronización principal para continuar.',
    needGoogleBeforeCreate: 'Inicia sesión con Google para continuar.',
    gistLinkedFromFirestore: 'Tu espacio social quedó vinculado automáticamente.',
    gistNotFoundCreated: 'Tu espacio social se creó correctamente.',
    signInAndLinked: 'Sesión iniciada correctamente.',
    profileMissing: 'Completa tu perfil para empezar en la actividad social.',
    profileSaved: 'Perfil social guardado correctamente.',
    signOut: 'Sesión social cerrada.',
    invalidSaveContext: 'No se pudo guardar ahora mismo. Inténtalo de nuevo.',
    missingSocialToken: 'No se pudo cargar tu espacio social. Vuelve a intentarlo.',
    firestoreCheckFailed: 'No se pudo verificar tu perfil social.',
    createGistFailed: 'No se pudo crear tu espacio social.',
    signInFailed: 'No se pudo iniciar sesión con Google.',
    loadProfileFailed: 'No se pudo cargar tu perfil social.',
    saveProfileFailed: 'No se pudo guardar tu perfil social.',
    maxFavoritesReached: 'Máximo de 5 juegos favoritos permitidos.',
    profileIncomplete: 'Para guardar tu perfil necesitas un nombre y al menos un juego favorito.',
    postPublished: 'Publicación compartida.',
    postPublishFailed: 'No se pudo compartir la publicación.',
    profileGamesRefreshFailed: 'No se pudieron actualizar los listados de este perfil.',
    refreshThrottled: 'Espera unos segundos antes de volver a actualizar.',
    friendRequestSent: 'Petición de amistad enviada.',
    friendRequestAccepted: 'Ahora sois amigos.',
    friendRequestCanceled: 'Petición cancelada.',
    friendRequestRejected: 'Petición rechazada.',
    friendRemoved: 'Amistad eliminada.',
    friendActionFailed: 'No se pudo completar la acción. Inténtalo de nuevo.',
  },
  steps: [
    { id: 'sync', title: 'GitHub', subtitle: 'Conectar' },
    { id: 'google', title: 'Google', subtitle: 'Validar' },
    { id: 'gist', title: 'Espacio social', subtitle: 'Crear' },
  ],
} as const;

/** Tipo de los textos de la UI social; usar en los componentes en lugar de `any`. */
export type SocialUiLabels = typeof SOCIAL_UI;
