import type { IconName } from './icons';
import { TAB_IDS, type TabId } from '../../model/types/game';
import type { ImportField } from '../../model/types/import';
import type { AdminAnomaly } from '../../model/types/firestore';

export interface TabAction {
  target: TabId;
  label: string;
  btnCls: string;
  icon: IconName;
}

export const TAB_ORDER: TabId[] = [...TAB_IDS];

export const TAB_TITLES: Record<TabId, string> = {
  c: 'Lista del completista',
  v: 'Lista de la vergüenza',
  e: 'En curso',
  p: 'Lista de próximos',
};

export const TAB_TOOLTIPS: Record<TabId, string> = {
  c: 'Completados',
  v: 'Abandonados',
  e: 'En curso',
  p: 'Próximos',
};

export const TAB_ROUTE: Record<TabId, string> = {
  c: '/completados',
  v: '/visitados',
  e: '/en-curso',
  p: '/proximos',
};

export const ROUTE_TAB: Record<string, TabId> = {
  '/completados': 'c',
  '/visitados': 'v',
  '/en-curso': 'e',
  '/proximos': 'p',
};

export const TAB_ACTIONS: Record<TabId, TabAction[]> = {
  c: [{ target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' }],
  v: [
    { target: 'c', label: 'Pasar a completados', btnCls: 'btn-complete', icon: 'trophy' },
    { target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' },
  ],
  e: [
    { target: 'c', label: 'Pasar a completados', btnCls: 'btn-complete', icon: 'trophy' },
    { target: 'v', label: 'Pasar a abandonados', btnCls: 'btn-abandoned', icon: 'abandoned' },
  ],
  p: [{ target: 'e', label: 'Pasar a en curso', btnCls: 'btn-playing', icon: 'play' }],
};

export const FILTER_BOOL: Record<TabId, { field: 'replayable' | 'retry'; label: string } | null> = {
  c: { field: 'replayable', label: 'Rejugar' },
  v: { field: 'retry', label: '¿Dar otra oportunidad?' },
  e: null,
  p: null,
};

export const SYNC_BADGE_TEXT = {
  idle: 'No sincronizado',
  ok: 'Sincronizado',
  syncing: 'Sincronizando…',
  error: 'Error de sincronización',
} as const;

export const DIALOG_MESSAGES = {
  deleteTagTitle: (tag: string) => `¿Eliminar etiqueta "${tag}"?`,
  cancel: 'Cancelar',
  confirmDelete: 'Eliminar',
} as const;

export const VALIDATION_MESSAGES = {
  yearInvalid: 'El año debe tener exactamente 4 dígitos. Pulsa Guardar de nuevo para ignorarlo.',
  fieldsInvalid: 'Revisa los campos marcados antes de guardar.',
  tagExists: 'Ya existe. Pulsa Guardar otra vez para fusionar.',
  tagMerged: 'Fusionado correctamente',
  tagUpdated: 'Actualizado correctamente',
  scoreRequired: 'Selecciona una puntuación',
} as const;

export const SYNC_MESSAGES = {
  needsConfiguration: 'Primero configura la sincronización.',
  connectSuccess: 'Sincronización configurada',
  connectError: 'Error al conectar sincronización',
  syncSuccess: 'Datos sincronizados',
  syncError: 'Error al sincronizar',
  initError: 'Error de sincronización',
  offline: 'Sin conexión: se reintentará al recuperar la red',
  syncInProgress: 'Sincronización ya en curso',
  disconnectSuccess: 'Sincronización desconectada',
  copySuccess: 'Gist ID copiado al portapapeles',
  copyError: 'No se pudo copiar el Gist ID',
  copyMissing: 'No hay Gist ID disponible para copiar',
  recoverSuccess: 'Gist ID recuperado desde Google',
  recoverMissingInProfile: 'No se encontró gamesGistId en tu perfil de Google/Firestore',
  recoverMissingTokenInProfile: 'No se encontró el token en tu perfil de Google/Firestore',
  recoverError: 'No se pudo recuperar el Gist ID desde Google',
} as const;

export const UI_MESSAGES = {
  admin: {
    noTags: 'No hay etiquetas',
    editPlaceholder: 'Escribe el nuevo valor',
    editBtn: 'Editar',
    deleteBtn: 'Eliminar',
    editCancelBtn: 'Cancelar',
    editSaveBtn: 'Guardar',
    closeAria: 'Cerrar modal',
  },
  form: {
    enterToAddHint: 'Pulsa Enter para añadir',
    newTitle: 'Nuevo juego',
    editTitle: 'Editar juego',
    nameLabel: 'Nombre *',
    namePlaceholder: 'Ej: The Witcher 3',
    genresLabel: 'Géneros',
    genresPlaceholder: 'Ej: Acción',
    platformsLabel: 'Plataformas',
    platformsPlaceholder: 'Ej: PC',
    scoreLabel: 'Puntuación',
    scoreToggle: 'Puntuar este juego',
    scoreToggleHint: 'Activa la puntuación de este juego. Si no la activas, no cuenta en la ruleta.',
    interestLabel: 'Interés',
    yearsLabel: 'Años completado',
    yearsPlaceholder: (year: number) => `Ej: ${year}`,
    hoursLabel: 'Horas jugadas',
    hoursPlaceholder: 'Ej: 120',
    strengthsLabel: 'Puntos fuertes',
    strengthsPlaceholder: 'Ej: Combate',
    weaknessesLabel: 'Puntos débiles',
    weaknessesPlaceholder: 'Ej: Repetitivo',
    reasonsLabel: 'Razones',
    reasonsPlaceholder: 'Ej: Falta de tiempo',
    steamDeck: 'Steam Deck',
    reviewLabel: 'Análisis',
    reviewPlaceholder: 'Ej: Historia sólida, combate excelente y gran ambientación.',
    charCount: (count: number, max: number) => `${count.toLocaleString()} / ${max.toLocaleString()} caracteres`,
    // A11y-3: mensajes de umbral para lectores de pantalla (texto constante por banda → se anuncian una vez al
    // cruzar el umbral, no en cada pulsación). El conteo numérico se deja como texto visible SIN aria-live.
    charNearLimit: 'Te acercas al límite de caracteres del análisis.',
    charLimitReached: 'Has alcanzado el límite de caracteres del análisis.',
    cancel: 'Cancelar',
    save: 'Guardar',
  },
  appTitle: 'Mis Listas',
  scrollTop: 'Volver arriba',
  nav: {
    ariaLabel: 'Navegación principal',
    lists: 'Listados',
    social: 'Social',
    settings: 'Ajustes',
    account: 'Cuenta',
    inbox: 'Bandeja',
    integrations: 'Integraciones',
  },
  import: {
    back: 'Volver',
    integrations: {
      title: 'Integraciones',
      note: 'Importa todos los juegos que ya tienes en tus tiendas, sin añadirlos a mano. Funciona con la app Playnite (solo Windows) y su extensión gratuita «Playnite Library Exporter», que crea un archivo con tu biblioteca. Los juegos llegan primero a la bandeja de importados para que tú decidas cuáles quedarte. Engloba las tiendas de PC (Steam, GOG, Epic, EA, Ubisoft, Amazon y Battle.net) y también las consolas de PlayStation y Xbox si en Playnite instalas sus complementos de biblioteca. Si un juego está en varias tiendas, se combinan sus plataformas en una sola entrada.',
      stepsTitle: 'Cómo traer tu biblioteca, paso a paso',
      steps: [
        'En tu PC con Windows, abre Playnite (si no la tienes, descárgala e instálala desde playnite.link).',
        'Dentro de Playnite, ve al menú principal (arriba a la izquierda) → «Complementos» → «Explorar complementos» y entra en la pestaña «Genérica».',
        'Busca «Playnite Library Exporter», pulsa «Instalar» y, cuando termine, cierra y vuelve a abrir Playnite.',
        'Abre de nuevo el menú principal → «Playnite Library Exporter» → «Export» y confirma. Deja el formato JSON (el que viene por defecto): se guardará un único archivo con extensión «.json».',
        'Vuelve a esta pantalla, pulsa «Importar de Playnite», elige ese archivo «.json» y tus juegos aparecerán en la bandeja de importados.',
      ],
      importBtn: 'Importar de Playnite',
      importAria: 'Seleccionar el archivo JSON exportado por Playnite Library Exporter',
      viewInbox: (n: number) => `Ver bandeja (${n})`,
      parseError: 'No se pudo leer el fichero. Comprueba que es el JSON exportado por «Playnite Library Exporter».',
      consoles: {
        psn: {
          title: 'Añadir tus juegos de PlayStation',
          steps: [
            'Abre Playnite en tu PC con Windows.',
            'Ve al menú principal (arriba a la izquierda) → «Complementos» → «Explorar complementos» y entra en la pestaña «Bibliotecas».',
            'Busca el complemento «PlayStation library integration» (hecho por la comunidad, de Xenor), pulsa «Instalar» y, al terminar, cierra y vuelve a abrir Playnite.',
            'Vuelve al menú principal → «Complementos» → ajustes de «PlayStation library integration» e inicia sesión con tu cuenta de PlayStation, siguiendo los pasos que te muestre.',
            'Tus juegos de PlayStation aparecerán en Playnite. Ahora solo tienes que exportarlos con «Playnite Library Exporter» (los pasos de más arriba) e importar el archivo aquí.',
          ],
        },
      },
    },
    inbox: {
      title: 'Bandeja de importados',
      note: 'Estos juegos se guardan en este equipo y caducan a los 30 días si no los clasificas.',
      sectionNew: 'Nuevos',
      sectionExisting: 'Ya en tus listas',
      empty: 'No hay juegos en la bandeja. Importa desde Integraciones.',
      goIntegrations: 'Ir a Integraciones',
      classifyTo: 'Clasificar en',
      discard: 'Descartar',
      clear: 'Vaciar bandeja',
      existingBadge: 'Ya en tus listas',
      suggested: 'sugerida',
      origin: 'Origen',
      game: 'Juego',
      selectAll: 'Seleccionar todo',
      selectRowAria: (name: string) => `Seleccionar ${name}`,
      deleteSelected: 'Eliminar seleccionados',
      selectedCount: (n: number) => `${n} seleccionado${n === 1 ? '' : 's'}`,
      search: 'Buscar por nombre',
      enrich: 'Actualizar en tus listas',
      enrichHint: 'Ya lo tienes: añade género/plataforma/horas que falten al juego de tu lista.',
      showing: (shown: number, total: number) => `Mostrando ${shown} de ${total}`,
      copyNameAria: (name: string) => `Copiar «${name}»`,
      copyNameSuccess: (name: string) => `«${name}» copiado`,
      copyNameError: 'No se pudo copiar el nombre',
      fields: {
        title: 'Qué datos traer',
        note: 'Se aplica a TODOS los juegos de la bandeja. El nombre siempre se traslada; lo que desmarques aquí no se copiará (podrás rellenarlo a mano en el formulario).',
        toggleShow: 'Ver qué datos traer',
        toggleHide: 'Ocultar qué datos traer',
        newGames: 'Al clasificar un juego nuevo',
        existingGames: 'Al actualizar uno que ya tienes',
        existingHint: 'Las plataformas y los géneros se SUMAN a los que ya tenga el juego (no se quita nada); las horas y la nota solo se rellenan si las tienes vacías.',
        labels: {
          platforms: 'Plataformas',
          genres: 'Géneros',
          hours: 'Horas',
          grade: 'Nota',
        } satisfies Record<ImportField, string>,
        fieldAria: (field: string, group: string) => `${field} — ${group}`,
        summary: (fields: string) => (fields ? `Se traen: ${fields}.` : 'No se trae ningún dato extra.'),
      },
    },
    notice: (added: number, merged: number, duplicates: number) =>
      `${added} añadido(s)` +
      (merged ? `, ${merged} fusionado(s)` : '') +
      (duplicates ? `, ${duplicates} duplicado(s) omitido(s)` : ''),
  },
  toolbar: {
    searchPlaceholder: 'Buscar',
    clearSearch: 'Limpiar búsqueda',
    toggleFilters: (open: boolean) => (open ? 'Ocultar filtros' : 'Mostrar filtros'),
    steamDeck: 'Steam Deck',
    removeFilter: (label: string) => `Quitar filtro ${label}`,
    genre: 'Género',
    allGenres: 'Todos los géneros',
    platform: 'Plataforma',
    allPlatforms: 'Todas las plataformas',
    score: 'Puntuación',
    anyScore: 'Cualquier puntuación',
    scoreOrMore: (value: number) => `${value} o más`,
    hours: 'Horas',
    anyDuration: 'Cualquier duración',
  },
  starPicker: {
    groupAria: 'Seleccionar puntuación',
    starAria: (star: number) => `${star} estrella${star > 1 ? 's' : ''}`,
  },
  table: {
    edit: 'Editar',
    delete: 'Eliminar',
    rowDetailsAria: (expanded: boolean, name: string) => `${expanded ? 'Contraer' : 'Expandir'} detalles de ${name}`,
    actionAria: (label: string, name: string) => `${label} - ${name}`,
    editAria: (name: string) => `Editar - ${name}`,
    deleteAria: (name: string) => `Eliminar - ${name}`,
    removeTag: (value: string) => `Eliminar ${value}`,
    emptyTitle: 'No hay juegos aquí todavía',
    emptyCta: 'Añadir juego',
    moreCount: (count: number) => `+${count}`,
    replayHeaderTip: 'Indica si el juego es rejugable',
    retryHeaderTip: 'Indica si merece otra oportunidad',
    sortHeaderTip: (column: string) => `Ordenar por ${column.toLowerCase()}`,
  },
  detail: {
    platforms: 'Plataformas',
    steamDeck: 'Steam Deck',
    genres: 'Géneros',
    yearsCompleted: 'Años en los que se completó',
    playtime: 'Tiempo jugado',
    hoursSuffix: (hours: string) => `${hours} horas`,
    strengths: 'Puntos fuertes',
    weaknesses: 'Puntos débiles',
    score: 'Puntuación',
    interest: 'Interés',
    replayability: 'Rejugabilidad',
    retry: 'Dar otra oportunidad',
    review: 'Análisis',
  },
  settings: {
    title: 'Ajustes',
    account: {
      title: 'Ajustes de cuenta',
    },
    // L2 — consentimiento de la analítica: banner previo y revocación desde la cuenta.
    analytics: {
      title: 'Analítica',
      subtitle: 'Estadísticas de uso anónimas (Google Analytics) para saber qué falla y qué se usa.',
      groupAria: 'Consentimiento de analítica',
      on: 'Activada',
      off: 'Desactivada',
      bannerTitle: 'Analítica opcional',
      bannerBody: 'Esta app puede usar Google Analytics para medir el uso y detectar errores. Requiere guardar identificadores en tu navegador, así que solo se activa si lo aceptas. Puedes cambiarlo cuando quieras en Cuenta.',
      bannerAccept: 'Aceptar',
      bannerReject: 'Rechazar',
      bannerMore: 'Política de cookies',
      bannerAria: 'Consentimiento de analítica',
    },
    // L3 — borrado de cuenta (RGPD art. 17).
    danger: {
      title: 'Zona de riesgo',
      deleteTitle: 'Borrar mi cuenta',
      deleteBody: 'Elimina tu perfil social, tus amistades y la configuración guardada en la nube, y borra los datos de este dispositivo (listas locales, sesión y token). No se puede deshacer.',
      deleteGistsNote: 'Tus Gists de GitHub NO se tocan: viven en tu cuenta de GitHub y solo tú puedes borrarlos.',
      deleteGistsLink: 'Ver mis Gists',
      deleteGistsUrl: 'https://gist.github.com',
      deleteBtn: 'Borrar cuenta',
      confirmTitle: '¿Borrar tu cuenta y los datos de este dispositivo?',
      confirmHint: 'Escribe BORRAR para confirmar.',
      confirmWord: 'BORRAR',
      confirmLabel: 'Borrar definitivamente',
      deleting: 'Borrando...',
      deletedOk: 'Cuenta borrada. Se han eliminado tus datos de la nube y de este dispositivo.',
      deletedPartial: 'Cuenta borrada con incidencias: algunos datos remotos no se pudieron eliminar. Vuelve a intentarlo o escribe al contacto de privacidad.',
      deleteError: 'No se pudo completar el borrado. Revisa la conexión e inténtalo de nuevo.',
    },
    // L4 — enlaces a los documentos legales.
    legal: {
      title: 'Legal',
      subtitle: 'Condiciones de uso, tratamiento de datos y cookies.',
      back: 'Volver',
      updated: (version: string) => `Última actualización: ${version}`,
      contact: 'Contacto',
    },
    appearance: {
      groupAria: 'Tema de la aplicación',
      light: 'Claro',
      dark: 'Oscuro',
      cycleHint: 'Pulsa para cambiar a',
      paletteAria: 'Paleta de color',
      paletteLabel: 'Tema',
      modeLabel: 'Modo',
      caseLabel: 'Texto',
      caseAria: 'Caja del texto de interfaz',
      caseNormal: 'Normal',
      caseUpper: 'Mayúsculas',
      steamLabel: 'Botón de Steam Deck',
      steamAria: 'Visibilidad del botón de Steam Deck',
      steamShow: 'Mostrar',
      steamHide: 'Ocultar',
      effectsLabel: 'Efectos visuales',
      effectsAria: 'Efectos visuales animados de los temas',
      effectsOn: 'Activados',
      effectsOff: 'Desactivados',
    },
    scoreScale: {
      title: 'Puntuación',
      subtitle: 'Cómo se muestran las notas de tus juegos.',
      groupAria: 'Escala de puntuación',
      starsLabel: 'Estrellas',
      starsHint: 'Escala clásica de 0 a 5',
      gradeLabel: 'Nota 0–100',
      gradeHint: 'Aro numérico, de rojo a verde',
      lockedHint: 'Asocia tu cuenta de Google para elegir la escala (se guarda y sincroniza entre dispositivos).',
    },
    sync: {
      title: 'Sincronización',
      status: 'Estado actual',
      gistConnectedPrefix: 'Gist conectado',
      helpGithubTitle: '¿Qué es GitHub Gist?',
      helpGithubBody: 'GitHub Gist permite guardar tus listas en la nube privada para sincronizarlas entre dispositivos.',
      helpConfigTitle: 'Cómo configurar',
      helpConfigBody: 'Necesitas una cuenta de GitHub y un token personal con permiso gist para conectar tu respaldo en la nube.',
      helpConfigLinkLabel: 'Abrir configuración de tokens en GitHub',
      helpConfigLinkUrl: 'https://github.com/settings/tokens',
      helpConfigExpand: 'Ver pasos detallados',
      helpConfigCollapse: 'Ocultar pasos detallados',
      helpConfigStep1: 'Inicia sesión en GitHub o crea una cuenta si aún no la tienes.',
      helpConfigStep2: 'Abre la página de tokens y crea un token nuevo.',
      helpConfigStep3: 'Asigna un nombre descriptivo para identificarlo fácilmente.',
      helpConfigStep4: 'En fecha de caducidad selecciona Sin caducidad (o el periodo que prefieras).',
      helpConfigStep5: 'En permisos marca gist y guarda el token.',
      helpConfigStep6: 'Copia el token y pégalo en el campo Token de esta pantalla. Mantén este valor en privado.',
      helpConfigStep7: 'Si es tu primera conexión, deja el Gist ID vacío. Si ya tenías uno, pégalo para reutilizarlo.',
      tokenLabel: 'Token *',
      tokenPlaceholder: 'ghp_xxxxxxxxxxxxxxxxxxxxxxx',
      gistLabel: 'Gist ID (vacío la primera vez)',
      gistPlaceholder: 'Ej: a1b2c3d4e5f6...',
      oauthConnectBtn: 'Conectar con GitHub',
      oauthConnectingBtn: 'Conectando con GitHub...',
      oauthHelpBody: 'La forma más sencilla: te lleva a GitHub, autorizas el acceso a tus gists y volvemos conectados. Sin crear ni pegar tokens.',
      manualToggleShow: 'Prefiero introducir un token manualmente',
      manualToggleHide: 'Ocultar el modo manual',
      connectBtn: 'Conectar',
      syncBtn: 'Sincronizar',
      disconnectBtn: 'Desconectar',
      copyBtn: 'Copiar Gist ID',
      recoverBtn: 'Recuperar de Google',
      recoveringBtn: 'Recuperando...',
      copyAriaLabel: 'Copiar Gist ID',
      recoverAriaLabel: 'Recuperar Gist ID desde Google',
    },
    backup: {
      title: 'Respaldo de datos',
      note: 'Control total sobre tus listas, tanto local como en la nube.',
      description: 'Exporta o importa tus listados en formato JSON.',
      overwriteLabel: 'Sobreescribir datos existentes (local y Gist)',
      overwriteHint: 'Marcar esta opción reemplaza por completo los datos almacenados y también actualizará tu Gist cuando haya sincronización activa.',
      exportBtn: 'Exportar',
      importBtn: 'Importar',
      importAriaLabel: 'Seleccionar archivo para importar',
    },
    admin: {
      title: 'Administración de filtros',
      description: 'Gestiona géneros, plataformas y etiquetas comunes por categoría.',
      genres: 'Géneros',
      platforms: 'Plataformas',
      strengths: 'Puntos fuertes',
      weaknesses: 'Puntos débiles / razón',
      collapseAria: 'Ocultar categoría',
      expandAria: 'Mostrar categoría',
    },
  },
} as const;

// Pantalla de reemplazo del error boundary RAÍZ (fallo de render que tumbaría toda la app).
export const APP_ERROR_UI = {
  sectionAria: 'Error de la aplicación',
  title: 'Algo ha ido mal',
  body: 'La aplicación ha encontrado un error inesperado. Vuelve a cargar la página para continuar; tus datos están a salvo.',
  reload: 'Recargar',
} as const;

// Panel de administración (`/admin`, ruta oculta). Nada que ver con `UI_MESSAGES.settings.admin`, que es la
// administración de ETIQUETAS de la propia biblioteca.
export const ADMIN_PANEL_UI = {
  sectionAria: 'Panel de administración',
  title: 'Administración',
  subtitle: 'Censo de usuarios con perfil social y acciones de moderación.',
  checking: 'Comprobando permisos...',
  loading: 'Cargando usuarios...',
  refresh: 'Actualizar',
  back: 'Volver a mis listas',
  searchLabel: 'Buscar',
  searchPlaceholder: 'Nombre o identificador',
  empty: 'No hay ningún perfil todavía.',
  emptyFiltered: 'Ningún perfil coincide con la búsqueda.',
  resultCount: (count: number) => (count === 1 ? '1 usuario' : `${count} usuarios`),
  // Aviso permanente: el panel enseña `profiles`, que no es el censo real de cuentas.
  scopeNote: 'Solo aparece quien tiene perfil social. Quien usa la app sin crearlo no es visible desde aquí: sus documentos son owner-only y las reglas no dejan leerlos ni al administrador.',
  // El saneado automático hace innecesaria la purga manual en cuanto el usuario vuelve a entrar. Conviene que se
  // vea, para que la purga manual se use solo donde de verdad aporta: en quien ya no vuelve.
  legacyNote: 'Los restos legacy se migran solos: cuando el usuario inicia sesión, su propio navegador pone a salvo el token y el id del gist en su configuración privada y limpia el perfil público. Purga a mano solo a quien lleve mucho sin entrar.',
  truncated: (limitCount: number) => `Se alcanzó el tope de ${limitCount} perfiles: la lista puede estar incompleta.`,
  totals: {
    aria: 'Resumen',
    profiles: 'Perfiles',
    socialEnabled: 'Con social activo',
    friendships: 'Amistades',
    pending: 'Solicitudes pendientes',
    legacy: 'Con restos legacy',
    flagged: 'Con señales',
  },
  // Ficha completa del usuario: todo lo que las reglas dejan leer de su documento y de sus amistades.
  field: {
    createdAt: 'Alta',
    createdAtEstimated: 'Alta (estimada)',
    createdAtUnknown: 'Sin fecha de alta',
    // Se dice de dónde sale la estimación para que no se confunda con un dato sellado.
    estimatedHint: 'Estimada a partir de su amistad más antigua: los perfiles creados antes de registrar la fecha de alta no la tienen.',
    lastActivity: 'Última actividad',
    lastFriendship: 'Último movimiento de amistad',
    friends: 'Amistades',
    pendingOut: 'Peticiones enviadas',
    pendingIn: 'Peticiones recibidas',
    profileId: 'Pseudónimo',
    socialGist: 'Gist social',
    schema: 'Esquema',
    photo: 'Foto',
    etag: 'ETag del gist',
    docId: 'Id del documento',
    yes: 'Sí',
    no: 'No',
    none: '—',
  },
  // Unificación del canal social cuando un usuario acabó con dos gists en circulación.
  gist: {
    driftTitle: 'Gists en circulación',
    profileGist: 'Publica en su perfil',
    friendGist: 'Sus amistades apuntan a',
    unifyBtn: 'Unificar canal social',
    unifyHint: 'Comprueba cuál de los dos gists es legible públicamente y cuál tiene el contenido, y deja ese en el perfil y en todas sus amistades.',
    confirm: (name: string) => `¿Unificar el canal social de ${name}? Se comprobará cuál de sus gists es el vivo (público y con contenido) y se escribirá ese en su perfil y en todas sus amistades. No se borra ningún gist.`,
    unifyDone: (gistId: string, friendships: number) =>
      `Canal unificado en ${gistId.slice(0, 8)}… (${friendships} ${friendships === 1 ? 'amistad corregida' : 'amistades corregidas'}).`,
    unifyAlready: 'Ya estaba unificado: no había nada que corregir.',
    unifyNoPublic: 'Ninguno de sus gists es legible sin autenticación, así que ninguno puede ser el canal vivo. Se arreglará cuando su cliente vuelva a publicar y lo haga público.',
    unifyNoEvidence: 'No se pudo leer ninguno de sus gists (sin red o límite de peticiones de GitHub agotado). No se ha tocado nada: inténtalo más tarde.',
    unifyPartial: 'Unificación incompleta: revisa la consola para el detalle.',
    // La guarda que evita perder de vista reseñas: mientras hay deriva, el hub FUSIONA los dos gists de un amigo,
    // así que unificar dejaría fuera lo que solo esté en el descartado.
    unifyBlocked: (winner: string, loser: string) =>
      `No se ha tocado nada: el gist descartado (${loser.slice(0, 8)}…) también tiene actividad, y ahora mismo la ves porque el hub fusiona los dos. Unificar en ${winner.slice(0, 8)}… la dejaría fuera. Fusionarlos requiere el token de su dueño, así que esto lo tiene que resolver su propio cliente al abrir el espacio social.`,
  },
  // Señales de algo fuera de lugar. Etiqueta corta para la píldora y explicación en el `title`.
  anomalies: {
    aria: 'Señales detectadas',
    'enabled-without-gist': {
      label: 'social sin gist',
      hint: 'Tiene el social activado pero no publica ningún gist: no sale en el directorio ni puede publicar nada. Perfil roto.',
    },
    'no-display-name': {
      label: 'sin nombre',
      hint: 'El perfil no tiene nick: se quedó a medio crear.',
    },
    'no-profile-id': {
      label: 'sin pseudónimo',
      hint: 'Nunca se estableció su identidad pseudónima (`profileId`): sus publicaciones no se pueden atribuir con estabilidad.',
    },
    'foreign-doc-id': {
      label: 'id ajeno al uid',
      hint: 'El documento no vive en `profiles/{uid}`: es de una versión anterior. Su email es la única forma de que su dueño lo recupere, así que no se le puede purgar.',
    },
    'legacy-fields': {
      label: 'restos legacy',
      hint: 'Arrastra email o id del gist de juegos en un documento que lee cualquier usuario autenticado.',
    },
    'legacy-token': {
      label: 'token en claro',
      hint: 'Guarda un token de GitHub sin cifrar, legible por cualquier usuario autenticado. Es lo más grave que puede quedar ahí.',
    },
    'stale-schema': {
      label: 'esquema antiguo',
      hint: 'El documento se escribió con una versión anterior del esquema y no se ha vuelto a guardar.',
    },
    'never-active': {
      label: 'sin actividad',
      hint: 'No tiene marca de actividad, así que no aparecería en un directorio ordenado por uso reciente.',
    },
    inactive: {
      label: 'inactivo +30 d',
      hint: 'Más de 30 días sin aparecer: la misma ventana con la que el feed deja de leer la actividad de un amigo.',
    },
    'future-activity': {
      label: 'fecha futura',
      hint: 'Su última actividad está fechada en el futuro: reloj del dispositivo desajustado o marca manipulada.',
    },
    'created-after-activity': {
      label: 'alta posterior a su actividad',
      hint: 'La fecha de alta es posterior a su última actividad, lo que no puede pasar salvo manipulación.',
    },
    'gist-drift': {
      label: 'gist divergente',
      hint: 'El gist social que publica no coincide con el que guardan sus amistades: sus reseñas no llegan al feed de sus amigos.',
    },
  } satisfies { aria: string } & Record<AdminAnomaly, { label: string; hint: string }>,
  tier: {
    column: 'Rango',
    selectAria: (name: string) => `Rango de ${name}`,
    // Mithril aparece deshabilitado en el resto de filas: se ve que existe y por qué no se puede dar.
    reservedHint: 'Reservado al administrador',
  },
  // Solo queda el nombre accesible de la lista: los encabezados de columna murieron con la tabla, que ahora es
  // una rejilla de fichas donde cada dato lleva su propia etiqueta.
  table: {
    aria: 'Usuarios',
  },
  noName: '(sin nombre)',
  // Identificación de quien tiene el perfil a medias. El correo NO está: se purgó del perfil público a propósito
  // (lo leía cualquier usuario autenticado). Para ponerle cara a un uid, la vía es la consola de Firebase Auth.
  knownAsHint: 'según sus amigos',
  copyUid: 'Copiar identificador',
  copiedUid: 'Identificador copiado.',
  enabled: 'Social activo',
  disabled: 'Social desactivado',
  never: 'Sin registro',
  legacyNone: 'Limpio',
  legacyEmail: 'email',
  legacyGamesGist: 'gist de juegos',
  legacyToken: 'token en claro',
  legacyAria: 'Restos legacy pendientes de purga',
  // Purga campo a campo: cada uno tiene una consecuencia distinta para su dueño y no son comparables.
  legacyPurgeAria: (field: string, name: string) => `Purgar ${field} de ${name}`,
  legacyEmailLocked: 'Este perfil no se identifica por el uid: su email es la única forma de que su dueño lo recupere, así que no se purga.',
  legacyConfirm: {
    email: (name: string) => `¿Borrar el email del perfil público de ${name}? Deja de ser legible por el resto de usuarios. Su dueño no lo nota: su perfil se localiza por el uid.`,
    gamesGistId: (name: string) => `¿Borrar el id del gist de juegos del perfil público de ${name}? No es un secreto (es un gist público), pero es el respaldo que usa "Recuperar Gist ID": si su configuración privada no lo tiene, tendrá que reintroducirlo a mano en un dispositivo nuevo.`,
    token: (name: string) => `¿Borrar el token de GitHub en claro de ${name}? Hoy lo puede leer cualquier usuario autenticado, así que conviene. Si aún no tiene el respaldo cifrado, la próxima vez que entre en un dispositivo nuevo tendrá que volver a conectar GitHub.`,
  },
  disableBtn: 'Desactivar social',
  enableBtn: 'Activar social',
  deleteBtn: 'Borrar perfil',
  working: 'Trabajando...',
  confirmDisable: (name: string) => `¿Desactivar el social de ${name}? Sale del directorio y del feed, pero conserva su perfil y sus amistades.`,
  confirmEnable: (name: string) => `¿Reactivar el social de ${name}?`,
  confirmDelete: (name: string) => `¿Borrar el perfil de ${name} y todas sus amistades? No se puede deshacer.`,
  deleteScope: 'No se borran su configuración privada (token cifrado), su cuenta de Google ni sus gists de GitHub: las reglas los reservan a su dueño. Al volver a entrar se le creará un perfil nuevo.',
  confirmCancel: 'Cancelar',
  confirmAccept: 'Confirmar',
  okTier: (tier: string) => `Rango cambiado a ${tier}.`,
  tierReservedWarning: 'Mithril está reservado a la cuenta del administrador.',
  okDisabled: 'Social desactivado.',
  okEnabled: 'Social reactivado.',
  okPurged: 'Campos legacy purgados.',
  okDeleted: 'Perfil y amistades borrados.',
  partialDeleted: 'Borrado incompleto: revisa la consola para el detalle.',
  errorGeneric: 'No se pudo completar la acción.',
} as const;

export const SOCIAL_UI = {
  hubTitle: 'Espacio social',
  loading: 'Cargando espacio social...',
  screenAria: 'Social',
  errorBoundary: {
    sectionAria: 'Error del espacio social',
    title: 'No se pudo mostrar el espacio social',
    body: 'Ha ocurrido un problema al cargar esta sección. El resto de la aplicación sigue disponible.',
    retry: 'Reintentar',
    // El reintento está limitado (1 cada 15 min) para no reintentar de forma indiscriminada ante un fallo persistente.
    retryIn: (minutes: number) => `Podrás reintentar en ${minutes} min`,
  },
  cardSelector: {
    searchLabel: 'Buscar',
    searchAria: (title: string) => `${title} buscador`,
    cardsAria: (title: string) => `${title} cards`,
  },
  gateway: {
    actionsAria: 'Acciones principales social',
    progressAria: 'Progreso de configuración social',
    stepsAria: 'Pasos de configuración social',
    stateAria: 'Estado de configuración social',
    flowAria: 'Flujo social',
    lead: 'Configura tu espacio social en tres pasos: conecta GitHub, valida con Google y crea tu espacio social.',
    stepCaption: (current: number, total: number) => `Paso actual: ${current} de ${total}`,
    progress: (value: number) => `${value}% completado`,
    connectSync: 'Ir a Sincronización',
    signIn: 'Continuar con Google',
    signingIn: 'Validando identidad...',
    resolveProfile: 'Comprobando perfil social...',
    createGist: 'Crear espacio social',
    creatingGist: 'Creando espacio social...',
    enterSocial: 'Entrar a la actividad',
    signOut: 'Cerrar sesión',
    syncRequired: 'Activa primero la sincronización principal con GitHub para habilitar el espacio social.',
    signInRequired: 'Tu sincronización principal está activa. Continúa con Google para validar tu perfil social.',
    gistRequired: 'Se ha verificado Firestore. Si no existe gist social asociado, crea un espacio social nuevo.',
    gistReadySignIn: 'Ya tienes gist social enlazado. Inicia sesión con Google para acceder a la actividad.',
    gistMissing: 'Aún no hay gist social enlazado.',
    detailsSummary: 'Ver estado técnico',
    stateSync: 'Sincronización',
    stateGist: 'Espacio social',
    stateSession: 'Sesión Google',
    stateConnected: 'Conectada a GitHub',
    stateNotConnected: 'No conectada',
    stateLinked: 'Enlazado',
    stateNotLinked: 'No enlazado',
    stateActive: 'Activa',
    stateNotStarted: 'No iniciada',
    flow: ['1. GitHub', '2. Google', '3. Espacio social', '4. Actividad'],
  },
  feed: {
    sectionAria: 'Social',
    title: 'Actividad social',
    subtitle: 'Descubre perfiles públicos, análisis y recomendaciones destacadas de otros jugadores.',
    actionsAria: 'Acciones de la actividad',
    activityListAria: 'Actividad social',
    toolbarAria: 'Búsqueda y filtros de la actividad',
    feedRowAria: 'Actividad social',
    profile: 'Editar mi perfil',
    openProfiles: 'Ver perfiles',
    openOwnProfile: 'Ver mi perfil',
    openRequests: 'Solicitudes',
    openRequestsAria: (count: number) =>
      count > 0 ? `Solicitudes de amistad, ${count} pendiente${count === 1 ? '' : 's'}` : 'Solicitudes de amistad',
    refresh: 'Actualizar',
    refreshing: 'Actualizando...',
    signOut: 'Cerrar sesión',
    statsProfiles: 'Perfiles visibles',
    statsActivities: 'Eventos de actividad',
    sectionTitle: 'Actividad de perfiles',
    activityTitle: 'Actividad',
    postsTitle: 'Publicaciones',
    postComposerLabel: 'Comparte una noticia o un enlace',
    postPlaceholder: 'Comparte una noticia o un enlace…',
    postPublish: 'Publicar',
    postPublishing: 'Publicando...',
    // Cupo por rango. El contador replica el de las reseñas (conteo visible + aviso solo en los umbrales).
    postCharCount: (count: number, max: number) => `${count.toLocaleString()} / ${max.toLocaleString()} caracteres`,
    postCharNearLimit: 'Te acercas al límite de caracteres de la publicación.',
    postCharLimitReached: 'Has alcanzado el límite de caracteres de la publicación.',
    postSharedFileHint: 'Pega la URL directa de la imagen (clic derecho → «Copiar la URL de la imagen») para verla incrustada.',
    postedAt: (date: Date) =>
      `Publicado el ${date.toLocaleDateString('es-ES', { day: '2-digit' })} de ${date.toLocaleDateString('es-ES', { month: 'long' })} a las ${date.toLocaleTimeString('es-ES', { hour: 'numeric', minute: '2-digit' })}`,
    loading: 'Cargando actividad...',
    empty: 'No hay perfiles visibles todavía o faltan permisos de lectura en Firestore.',
    activityEmpty: 'Aún no hay actividad de análisis para mostrar.',
    activityEmptyNoFriends: 'Tu feed muestra la actividad de tus amigos. Descubre perfiles y añade amigos para empezar a ver sus análisis y publicaciones.',
    discoverFriends: 'Descubre y añade amigos',
    openActivityAria: (name: string, gameName: string) => `Abrir detalle de actividad de ${name} sobre ${gameName}`,
    openProfileAria: (name: string) => `Abrir perfil social de ${name}`,
    analyzedRecently: 'Analizado recientemente',
    feedLoadMore: 'Mostrar más',
    analyzedAt: (date: Date) =>
      `Analizado el ${date.toLocaleDateString('es-ES', { day: '2-digit' })} de ${date.toLocaleDateString('es-ES', { month: 'long' })} a las ${date.toLocaleTimeString('es-ES', { hour: 'numeric', minute: '2-digit' })}`,
    reviewHeadline: (gameName: string) => `Analizó ${gameName}`,
    reviewEmpty: 'Sin comentario adicional en el análisis.',
    showMore: 'Más',
    viewDetail: 'Ver detalle',
    detailTitle: 'Detalle de actividad social',
    detailSubtitle: 'Contenido completo del análisis seleccionado.',
    detailActionsAria: 'Acciones del detalle social',
    detailMissing: 'No se encontró la actividad solicitada o ya no está disponible.',
    metadataPlatforms: 'Plataformas:',
    metadataGenres: 'Géneros:',
    metadataStrengths: 'Puntos fuertes:',
    metadataWeaknesses: 'Puntos débiles:',
    profileDetailTitle: 'Detalle de perfil social',
    profileDetailSubtitle: 'Vista pública del perfil seleccionado.',
    profileDetailActionsAria: 'Acciones del detalle de perfil social',
    profileDetailMissing: 'No se encontró el perfil solicitado o ya no está disponible.',
    profileListsTitle: 'Juegos',
    roulettePick: 'Elige tu próximo juego',
    profileListsEmpty: 'Este perfil no ha publicado listados todavía.',
    profileFriendsOnly: 'Hazte amigo de este jugador para ver sus reseñas, listados y recomendaciones.',
    profileFriendsOnlyTitle: 'Perfil de amigos',
    gameFilterPlaceholder: 'Filtrar por título…',
    gameFilterEmpty: 'Ningún juego coincide con la búsqueda.',
    profileDetailRefresh: 'Actualizar listados',
    profileDetailRefreshing: 'Actualizando…',
    reviewsButton: 'Reseñas',
    reviewsBack: 'Ver perfil',
    reviewsTitle: 'Reseñas',
    reviewsEmptyProfile: 'Este perfil no ha publicado reseñas todavía.',
    reviewExpand: 'Ver más',
    reviewCollapse: 'Ver menos',
    reviewOpenAria: (gameName: string) => `Abrir la reseña de ${gameName}`,
    reviewDetailTitle: 'Reseña',
    reviewDetailSubtitle: 'Análisis completo de este juego.',
    reviewsBackToList: 'Volver a las reseñas',
    profileListTabCompleted: 'Completados',
    profileListTabVisited: 'Abandonados',
    profileListTabPlaying: 'En curso',
    profileListTabPlanned: 'Próximos',
    backToFeed: 'Volver a la actividad',
    searchLabel: 'Buscar perfiles',
    searchPlaceholder: 'Buscar por nombre, email o juego',
    filterAll: 'Todos',
    resultCount: (count: number) => `${count} perfiles visibles`,
  },
  profiles: {
    sectionAria: 'Perfiles sociales',
    title: 'Perfiles',
    subtitle: 'Descubre perfiles públicos de otros jugadores.',
    actionsAria: 'Acciones de la pantalla de perfiles',
    toolbarAria: 'Filtro de perfiles por nombre',
    rowAria: 'Perfiles públicos',
    back: 'Volver a la actividad',
    refresh: 'Actualizar',
    refreshing: 'Actualizando...',
    searchLabel: 'Buscar por nombre',
    searchPlaceholder: 'Filtrar perfiles por nombre',
    resultCount: (count: number) => `${count} perfiles visibles`,
    loading: 'Cargando perfiles...',
    empty: 'No hay perfiles visibles todavía o faltan permisos de lectura en Firestore.',
    openProfileAria: (name: string) => `Abrir perfil social de ${name}`,
    friendsTitle: 'Amigos',
    othersTitle: 'Descubrir',
    friendsEmpty: 'Aún no tienes amigos. Envía una petición desde la lista de abajo.',
    othersEmpty: 'No hay más perfiles que mostrar.',
  },
  requests: {
    sectionAria: 'Solicitudes de amistad',
    title: 'Solicitudes de amistad',
    subtitle: 'Gestiona las peticiones que recibes y las que has enviado.',
    actionsAria: 'Acciones de solicitudes de amistad',
    back: 'Volver a la actividad',
    incomingTitle: 'Recibidas',
    outgoingTitle: 'Enviadas',
    friendsTitle: 'Amigos',
    incomingEmpty: 'No tienes peticiones de amistad pendientes.',
    outgoingEmpty: 'No has enviado peticiones pendientes.',
    friendsEmpty: 'Aún no tienes amigos. Envía peticiones desde Perfiles.',
    loading: 'Cargando solicitudes...',
    accept: 'Aceptar',
    reject: 'Rechazar',
    cancel: 'Cancelar',
    remove: 'Dejar de ser amigos',
    acceptAria: (name: string) => `Aceptar la petición de ${name}`,
    rejectAria: (name: string) => `Rechazar la petición de ${name}`,
    cancelAria: (name: string) => `Cancelar la petición enviada a ${name}`,
    removeAria: (name: string) => `Dejar de ser amigo de ${name}`,
    unknownUser: 'Usuario',
  },
  friendship: {
    add: 'Añadir amigo',
    accept: 'Aceptar',
    pending: 'Pendiente',
    friends: 'Amigos',
    remove: 'Dejar de ser amigos',
    addAria: (name: string) => `Enviar petición de amistad a ${name}`,
    acceptAria: (name: string) => `Aceptar la petición de ${name}`,
    cancelAria: (name: string) => `Cancelar la petición enviada a ${name}`,
    removeAria: (name: string) => `Dejar de ser amigo de ${name}`,
    removeConfirmTitle: (name: string) => `¿Dejar de ser amigo de ${name}?`,
    removeConfirmAction: 'Dejar de ser amigos',
  },
  profile: {
    sectionAria: 'Social',
    actionsAria: 'Acciones del perfil social',
    title: 'Mi perfil social',
    subtitle: 'Define tu identidad pública y mantén tu perfil sincronizado.',
    toFeed: 'Ir a la actividad',
    save: 'Guardar perfil',
    saving: 'Guardando perfil...',
    signOut: 'Cerrar sesión',
    statusSynced: 'Sincronizado',
    statusUnpublished: 'Sin publicar',
    identityTitle: 'Identidad visible',
    identityDescription: 'Este nombre se mostrará en la actividad social y en análisis compartidos.',
    nameLabel: 'Nombre social',
    namePlaceholder: 'Escribe tu nombre visible',
    needsCompletedGames: 'Necesitas al menos un juego completado en tus listas para poder crear tu perfil social.',
    privacyTitle: 'Privacidad',
    privacyLabel: 'Perfil privado',
    privacyPrivate: 'Tu perfil es privado. Solo usuarios autorizados podrán verlo.',
    privacyPublic: 'Tu perfil es público. Otros usuarios podrán encontrarte por email.',
    hydrating: 'Cargando datos de perfil desde gist social...',
    visibilityTitle: 'Visibilidad del perfil',
    visibilityDescription: 'Configura qué partes de tus listados se comparten públicamente en el detalle social.',
    hideListSectionTitle: 'Ocultar listados',
    hideVisitedList: 'Ocultar lista de abandonados',
    hidePlayingList: 'Ocultar lista de en curso',
    hidePlannedList: 'Ocultar lista de próximos',
    hideFieldSectionTitle: 'Ocultar campos',
    hideReplayableField: 'Rejugar',
    hideRetryField: 'Dar otra oportunidad',
    hideGameTimeField: 'Tiempo jugado',
    photoSectionTitle: 'Foto de perfil',
    showPhotoField: 'Mostrar mi foto de perfil',
  },
  status: {
    needMainSync: 'Activa la sincronización principal para continuar.',
    needGoogleBeforeCreate: 'Inicia sesión con Google para continuar.',
    gistLinkedFromFirestore: 'Tu espacio social quedó vinculado automáticamente.',
    gistNotFoundCreated: 'Tu espacio social se creó correctamente.',
    signInAndLinked: 'Sesión iniciada correctamente.',
    profileMissing: 'Completa tu perfil para empezar en la actividad social.',
    profileSaved: 'Perfil social guardado correctamente.',
    signOut: 'Sesión social cerrada.',
    invalidSaveContext: 'No se pudo guardar ahora mismo. Inténtalo de nuevo.',
    missingSocialToken: 'No se pudo cargar tu espacio social. Vuelve a intentarlo.',
    firestoreCheckFailed: 'No se pudo verificar tu perfil social.',
    createGistFailed: 'No se pudo crear tu espacio social.',
    signInFailed: 'No se pudo iniciar sesión con Google.',
    loadProfileFailed: 'No se pudo cargar tu perfil social.',
    saveProfileFailed: 'No se pudo guardar tu perfil social.',
    profileIncomplete: 'Para guardar tu perfil necesitas un nombre y al menos un juego completado.',
    // Fallo por credencial al leer el canal de un amigo: no es que no haya publicado, es que el token no vale.
    socialReadUnauthorized: 'No se pudo leer la actividad de alguna de tus amistades: tu conexión con GitHub ha caducado. Vuelve a conectarla en Ajustes.',
    postPublished: 'Publicación compartida.',
    postPublishFailed: 'No se pudo compartir la publicación.',
    profileGamesRefreshFailed: 'No se pudieron actualizar los listados de este perfil.',
    refreshThrottled: 'Espera unos segundos antes de volver a actualizar.',
    friendRequestSent: 'Petición de amistad enviada.',
    friendRequestAccepted: 'Ahora sois amigos.',
    friendRequestCanceled: 'Petición cancelada.',
    friendRequestRejected: 'Petición rechazada.',
    friendRemoved: 'Amistad eliminada.',
    friendActionFailed: 'No se pudo completar la acción. Inténtalo de nuevo.',
  },
  steps: [
    { id: 'sync', title: 'GitHub', subtitle: 'Conectar' },
    { id: 'google', title: 'Google', subtitle: 'Validar' },
    { id: 'gist', title: 'Espacio social', subtitle: 'Crear' },
  ],
} as const;

/** Tipo de los textos de la UI social; usar en los componentes en lugar de `any`. */
export type SocialUiLabels = typeof SOCIAL_UI;
