// Textos de la pantalla de Ajustes y de las tarjetas que la componen (apariencia, escala, sincronización,
// respaldo, zona peligrosa, legal).
//
// Aparte de `labels.ts` por peso y por orden: son ~11 kB que solo consumen chunks perezosos (`SettingsHub`,
// `AccountHub`, `LegalScreen`…), mientras que `labels.ts` viaja en el arranque.
//
// El texto de la ANALÍTICA se quedó fuera a propósito, en `labels.ts`: lo pinta `ConsentBanner`, que se monta con
// la aplicación, y traerlo aquí devolvería estos 11 kB al chunk de entrada por catorce líneas.
export const SETTINGS_UI = {
  title: 'Ajustes',
  account: {
    title: 'Ajustes de cuenta',
  },
  // L3 — borrado de cuenta (RGPD art. 17).
  danger: {
    title: 'Zona de riesgo',
    deleteTitle: 'Borrar mi cuenta',
    deleteBody: 'Elimina tu perfil social, tus amistades y la configuración guardada en la nube, y borra los datos de este dispositivo (listas locales, sesión y token). No se puede deshacer.',
    deleteGistsNote: 'Tus Gists de GitHub NO se tocan al borrar la cuenta: viven en tu cuenta y solo tú puedes borrarlos. (La única excepción, ajena a este borrado, es la retirada del canal social antiguo que la app migró a no listado.)',
    deleteGistsLink: 'Ver mis Gists',
    deleteGistsUrl: 'https://gist.github.com',
    deleteBtn: 'Borrar cuenta',
    confirmTitle: '¿Borrar tu cuenta y los datos de este dispositivo?',
    confirmHint: 'Escribe BORRAR para confirmar.',
    confirmWord: 'BORRAR',
    confirmLabel: 'Borrar definitivamente',
    deleting: 'Borrando...',
    deletedOk: 'Cuenta borrada. Se han eliminado tus datos de la nube y de este dispositivo.',
    deletedPartial: 'Cuenta borrada con incidencias: algunos datos remotos no se pudieron eliminar. Vuelve a intentarlo o escribe al contacto de privacidad.',
    deleteError: 'No se pudo completar el borrado. Revisa la conexión e inténtalo de nuevo.',
  },
  // L4 — enlaces a los documentos legales.
  legal: {
    title: 'Legal',
    subtitle: 'Condiciones de uso, tratamiento de datos y cookies.',
    back: 'Volver',
    updated: (version: string) => `Última actualización: ${version}`,
    contact: 'Contacto',
  },
  scoreScale: {
    title: 'Puntuación',
    subtitle: 'Cómo se muestran las notas de tus juegos.',
    groupAria: 'Escala de puntuación',
    starsLabel: 'Estrellas',
    starsHint: 'Escala clásica de 0 a 5',
    gradeLabel: 'Nota 0–100',
    gradeHint: 'Aro numérico, de rojo a verde',
    lockedHint: 'Asocia tu cuenta de Google para elegir la escala (se guarda y sincroniza entre dispositivos).',
  },
  sync: {
    title: 'Sincronización',
    status: 'Estado actual',
    gistConnectedPrefix: 'Gist conectado',
    helpGithubTitle: '¿Qué es GitHub Gist?',
    helpGithubBody: 'GitHub Gist permite guardar tus listas en la nube privada para sincronizarlas entre dispositivos.',
    helpConfigTitle: 'Cómo configurar',
    helpConfigBody: 'Necesitas una cuenta de GitHub y un token personal con permiso gist para conectar tu respaldo en la nube.',
    helpConfigLinkLabel: 'Abrir configuración de tokens en GitHub',
    helpConfigLinkUrl: 'https://github.com/settings/tokens',
    helpConfigExpand: 'Ver pasos detallados',
    helpConfigCollapse: 'Ocultar pasos detallados',
    helpConfigStep1: 'Inicia sesión en GitHub o crea una cuenta si aún no la tienes.',
    helpConfigStep2: 'Abre la página de tokens y crea un token nuevo.',
    helpConfigStep3: 'Asigna un nombre descriptivo para identificarlo fácilmente.',
    helpConfigStep4: 'En fecha de caducidad selecciona Sin caducidad (o el periodo que prefieras).',
    helpConfigStep5: 'En permisos marca gist y guarda el token.',
    helpConfigStep6: 'Copia el token y pégalo en el campo Token de esta pantalla. Mantén este valor en privado.',
    helpConfigStep7: 'Si es tu primera conexión, deja el Gist ID vacío. Si ya tenías uno, pégalo para reutilizarlo.',
    tokenLabel: 'Token *',
    tokenPlaceholder: 'ghp_xxxxxxxxxxxxxxxxxxxxxxx',
    tokenToggle: (shown: boolean) => (shown ? 'Ocultar el token' : 'Mostrar el token'),
    gistLabel: 'Gist ID (vacío la primera vez)',
    gistPlaceholder: 'Ej: a1b2c3d4e5f6...',
    oauthConnectBtn: 'Conectar con GitHub',
    oauthConnectingBtn: 'Conectando con GitHub...',
    oauthHelpBody: 'La forma más sencilla: te lleva a GitHub, autorizas el acceso a tus gists y volvemos conectados. Sin crear ni pegar tokens.',
    manualToggleShow: 'Prefiero introducir un token manualmente',
    manualToggleHide: 'Ocultar el modo manual',
    connectBtn: 'Conectar',
    syncBtn: 'Sincronizar',
    disconnectBtn: 'Desconectar',
    copyBtn: 'Copiar Gist ID',
    recoverBtn: 'Recuperar de Google',
    recoveringBtn: 'Recuperando...',
    copyAriaLabel: 'Copiar Gist ID',
    recoverAriaLabel: 'Recuperar Gist ID desde Google',
  },
  backup: {
    title: 'Respaldo de datos',
    note: 'Control total sobre tus listas, tanto local como en la nube.',
    description: 'Exporta o importa tus listados en formato JSON.',
    overwriteLabel: 'Sobreescribir datos existentes (local y Gist)',
    overwriteHint: 'Marcar esta opción reemplaza por completo los datos almacenados y también actualizará tu Gist cuando haya sincronización activa.',
    exportBtn: 'Exportar',
    importBtn: 'Importar',
    importAriaLabel: 'Seleccionar archivo para importar',
  },
  admin: {
    title: 'Administración de filtros',
    description: 'Gestiona géneros, plataformas y etiquetas comunes por categoría.',
    genres: 'Géneros',
    platforms: 'Plataformas',
    strengths: 'Puntos fuertes',
    weaknesses: 'Puntos débiles / razón',
    collapseAria: 'Ocultar categoría',
    expandAria: 'Mostrar categoría',
  },
} as const;
